[package]
name = "coins-bip39"
version = "0.1.0"
authors = ["Rohit Narurkar <rohit.narurkar@protonmail.com>"]
edition = "2018"
description = "Bip39 in Rust"
repository = "https://github.com/summa-tx/bitcoins-rs"
license = "MIT OR Apache-2.0"

[dependencies]
bitvec = "0.17.4"
coins-bip32 = { path = "../bip32" }
hex = "0.4.2"
hmac = "0.10.1"
pbkdf2 = "0.7.3"
rand = "0.7.0"
sha2 = "0.9.3"
thiserror = "1.0"
